<a href="https://colab.research.google.com/github/domysolano/NumPy-Basic-Matrix-Operations/blob/main/NumPyBasicMatrixOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Maestría en Inteligencia Artificial y Analítica de Datos**

Curso: *Programación para Analítica Descriptiva y Predictiva*

* Semestre: Enero-Junio 2026.
* Profesor: Dr. Vicente García Jiménez.
* Alumno: Ricardo Solano Monje.
* Matrícula: 266221.
* Unidad 1.
* Práctica 4: Manipulación de matrices.
* Objetivo de la práctica: Usar NumPy para crear matrices y realizar algunas operaciones básicas sobre éstas.
* Realizado por: Ricardo Solano Monje.

# NumPy: *Basic Matrix Operations*

### Manipulación de matrices.

* Crea dos matrices de 3x3 con números aleatorios entre 1 y 10. *Realiza las siguientes operaciones:*
  * Suma ambas matrices,
  * Resta la segunda matriz de la primera,
  * Multiplica la primera matriz por 2,
  * Realiza una multiplicación matricial entre las dos matrices.

## Broadcasting in NumPy.

Thanks to NumPy, Array Operations is where Python becomes magic. *Broadcasting is NumPy-specific* (regular Python lists DON'T support broadcasting) but follows Python's philosophy of making *common operations easy and intuitive*. However, it's not a general Python language feature.

### What is Broadcasting?
Broadcasting allows NumPy to perform operations on arrays of different shapes by "stretching" the smaller array to match the larger one's shape.

In NumPy, the operation result = array + 10 (where array is [1, 2, 3, 4])
uses broadcasting to add the scalar value \(10\) to every element of the array.
It does this by conceptually "stretching" the scalar into an array of the same shape as the original array,
enabling efficient, element-wise addition.

### The Broadcasting Rules

NumPy follows strict rules for broadcasting. Two arrays are broadcastable if:

* Rule 1: Dimensions are aligned from the RIGHT.
* Rule 2: Dimensions must be equal OR one of them must be 1
* Rule 3: Missing dimensions are treated as 1

In [1]:
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 2.0.2


### I. Create Two 3x3 Matrices with random numbers between 1 and 100

In [2]:
### Create Two 3x3 Matrices with Random Numbers (1-10) (inclusive)
# Set random seed for reproducibility
np.random.seed(42)
# Create A matrix 3x3
matrixA = np.random.randint(1, 11, size=(3, 3))
print(f"Matrix A {matrixA.shape}:")
print(matrixA)
print()

# Create B matrix 3x3
matrixB = np.random.randint(1, 11, size=(3, 3))
print(f"Matrix B {matrixB.shape}:")
print(matrixB)

Matrix A (3, 3):
[[ 7  4  8]
 [ 5  7 10]
 [ 3  7  8]]

Matrix B (3, 3):
[[5 4 8]
 [8 3 6]
 [5 2 8]]


## *II. Carry out the following Operations:*

* *1: Add both matrices.*

In [3]:
print("1. Matrix Addition C=(A + B)")
print("Matrix A:")
print(matrixA)
print("\nMatrix B:")
print(matrixB)

# Element-wise addition
matrixC = matrixA + matrixB
print("\nMatrix C= (A + B):")
print(matrixC)

# Visual computing
print("\nVisual computing C:")
for i in range(3):
    for j in range(3):
        print(f"  {matrixC[i,j]:3d} = {matrixA[i,j]:2d} + {matrixB[i,j]:2d}  ", end="  ")
    print()

1. Matrix Addition C=(A + B)
Matrix A:
[[ 7  4  8]
 [ 5  7 10]
 [ 3  7  8]]

Matrix B:
[[5 4 8]
 [8 3 6]
 [5 2 8]]

Matrix C= (A + B):
[[12  8 16]
 [13 10 16]
 [ 8  9 16]]

Visual computing C:
   12 =  7 +  5        8 =  4 +  4       16 =  8 +  8    
   13 =  5 +  8       10 =  7 +  3       16 = 10 +  6    
    8 =  3 +  5        9 =  7 +  2       16 =  8 +  8    


* *2: Subtract the second matrix from the first one, C=(A - B)*

In [4]:
print("2. Matrix Subtraction C=(A - B)")
print("Matrix A:")
print(matrixA)
print("\nMatrix B:")
print(matrixB)

# Element-wise subtraction
matrixC = matrixA - matrixB
print("\nC=(A - B):")
print(matrixC)

# Visual representation
print("\nVisual computing C:")
for i in range(3):
    for j in range(3):
        print(f"  {matrixC[i,j]:3d}={matrixA[i,j]:2d} - {matrixB[i,j]:2d} ", end="  ")
    print()

2. Matrix Subtraction C=(A - B)
Matrix A:
[[ 7  4  8]
 [ 5  7 10]
 [ 3  7  8]]

Matrix B:
[[5 4 8]
 [8 3 6]
 [5 2 8]]

C=(A - B):
[[ 2  0  0]
 [-3  4  4]
 [-2  5  0]]

Visual computing C:
    2= 7 -  5       0= 4 -  4       0= 8 -  8   
   -3= 5 -  8       4= 7 -  3       4=10 -  6   
   -2= 3 -  5       5= 7 -  2       0= 8 -  8   


* *3. Multiply First Matrix by 2*

Scalar multiplication C=2*A IS broadcasting, but it's the simplest form of broadcasting.

In [5]:
# For Broadcasting the operation to all elements of the matrix, just times 2, NumPy will do the job

print("3. Scalar Multiplication C=2*A")
print("Matrix A:")
print(matrixA)
# Scalar multiplication using broadcast propagation.
matrixC = matrixA * 2
print("\nC=2*A:")
print(matrixC)

# Using np.multiply() method, old fashion approach.
matrixC2 = np.multiply(matrixA, 2)
print("\nUsing np.multiply(matrixA, 2):")
print(matrixC2)

# Verifying same results using boolean match
print(f"\nare results identical?: {np.array_equal(matrixC, matrixC2)}")


3. Scalar Multiplication C=2*A
Matrix A:
[[ 7  4  8]
 [ 5  7 10]
 [ 3  7  8]]

C=2*A:
[[14  8 16]
 [10 14 20]
 [ 6 14 16]]

Using np.multiply(matrixA, 2):
[[14  8 16]
 [10 14 20]
 [ 6 14 16]]

are results identical?: True


* *4: Perform a matrix multiplication between the two matrices.*

In [6]:
print("=== 4. Matrix Multiplication (A · B) ===")
print("Matrix A:")
print(matrixA)
print("\nMatrix B:")
print(matrixB)

# Matrix multiplication (dot product), old fashion
matrixC = np.dot(matrixA, matrixB)
print("\nC=(A · B):")
print(matrixC)

# Alternative method using @ operator, it acts as operator overloading, easier to read in math formulas!
# The @ (matrix multiplication) operator was introduced in Python 3.5
matrixC2 = matrixA @ matrixB
print("\nUsing @ operator: C= (A @ B)")
print(matrixC2)

# Manual calculation explanation
print("\n=== How Matrix Multiplication Works ===")
print("For a 3x3 matrix multiplication C = A · B:")
print("C[i,j] = A[i,0]×B[0,j] + A[i,1]×B[1,j] + A[i,2]×B[2,j]")
print()

# Show calculation for first element
print("Example: Calculating C[0,0]:")
a_row = matrixA[0, :]  # First row of A
b_col = matrixB[:, 0]  # First column of B
print(f"  A[0,:] = {a_row}")
print(f"  B[:,0] = {b_col}")
c_00 = np.dot(a_row, b_col)
print(f"  C[0,0] = ({a_row[0]}×{b_col[0]}) + ({a_row[1]}×{b_col[1]}) + ({a_row[2]}×{b_col[2]})")
print(f"        = {a_row[0]*b_col[0]} + {a_row[1]*b_col[1]} + {a_row[2]*b_col[2]}")
print(f"        = {c_00}")
print(f"  From result matrix: {matrixC[0,0]}")

=== 4. Matrix Multiplication (A · B) ===
Matrix A:
[[ 7  4  8]
 [ 5  7 10]
 [ 3  7  8]]

Matrix B:
[[5 4 8]
 [8 3 6]
 [5 2 8]]

C=(A · B):
[[107  56 144]
 [131  61 162]
 [111  49 130]]

Using @ operator: C= (A @ B)
[[107  56 144]
 [131  61 162]
 [111  49 130]]

=== How Matrix Multiplication Works ===
For a 3x3 matrix multiplication C = A · B:
C[i,j] = A[i,0]×B[0,j] + A[i,1]×B[1,j] + A[i,2]×B[2,j]

Example: Calculating C[0,0]:
  A[0,:] = [7 4 8]
  B[:,0] = [5 8 5]
  C[0,0] = (7×5) + (4×8) + (8×5)
        = 35 + 32 + 40
        = 107
  From result matrix: 107
